services:
  - type: web
    name: sai-marketing-medical-agencies
    env: node
    plan: free
    branch: main
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
